# Rana-Roop Singh Bhullar

## CA06 - kNN 

In [19]:
# Import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors

In [20]:
# Read the data
movies = pd.read_csv('https://github.com/ArinB/CA05-kNN/raw/master/movies_recommendation_data.csv')

In [21]:
# Checking if data was read correctly
movies.head()

Movie ID          Movie Name  IMDB Rating  Biography  Drama  Thriller  \
0        58  The Imitation Game          8.0          1      1         1   
1         8          Ex Machina          7.7          0      1         0   
2        46    A Beautiful Mind          8.2          1      1         0   
3        62   Good Will Hunting          8.3          0      1         0   
4        97        Forrest Gump          8.8          0      1         0   

   Comedy  Crime  Mystery  History  Label  
0       0      0        0        0      0  
1       0      0        1        0      0  
2       0      0        0        0      0  
3       0      0        0        0      0  
4       0      0        0        0      0

In [22]:
movies.tail()

Movie ID                        Movie Name  IMDB Rating  Biography  Drama  \
25        17                    Thor: Ragnarok          7.9          0      0   
26        12  Spirit: Stallion of the Cimarron          7.1          0      0   
27         1                     Hacksaw Ridge          8.2          1      1   
28        86                  12 Years a Slave          8.1          1      1   
29        46                    Queen of Katwe          7.4          1      1   

    Thriller  Comedy  Crime  Mystery  History  Label  
25         0       1      0        0        0      0  
26         0       0      0        0        0      0  
27         0       0      0        0        1      0  
28         0       0      0        0        1      0  
29         0       0      0        0        0      0

### Data Quality Analysis

In [23]:
# Total rows and columns
movies.shape

(30, 11)

In [24]:
# Range, column, number of non-null objects, data type, memory usage
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Movie ID     30 non-null     int64  
 1   Movie Name   30 non-null     object 
 2   IMDB Rating  30 non-null     float64
 3   Biography    30 non-null     int64  
 4   Drama        30 non-null     int64  
 5   Thriller     30 non-null     int64  
 6   Comedy       30 non-null     int64  
 7   Crime        30 non-null     int64  
 8   Mystery      30 non-null     int64  
 9   History      30 non-null     int64  
 10  Label        30 non-null     int64  
dtypes: float64(1), int64(9), object(1)
memory usage: 2.7+ KB


In [25]:
# Descriptive statistics for the dataset
movies.describe()

Movie ID  IMDB Rating  Biography      Drama   Thriller     Comedy  \
count  30.000000    30.000000  30.000000  30.000000  30.000000  30.000000   
mean   48.133333     7.696667   0.233333   0.600000   0.100000   0.100000   
std    29.288969     0.666169   0.430183   0.498273   0.305129   0.305129   
min     1.000000     5.900000   0.000000   0.000000   0.000000   0.000000   
25%    27.750000     7.300000   0.000000   0.000000   0.000000   0.000000   
50%    48.500000     7.750000   0.000000   1.000000   0.000000   0.000000   
75%    64.250000     8.175000   0.000000   1.000000   0.000000   0.000000   
max    98.000000     8.800000   1.000000   1.000000   1.000000   1.000000   

           Crime    Mystery    History  Label  
count  30.000000  30.000000  30.000000   30.0  
mean    0.133333   0.100000   0.100000    0.0  
std     0.345746   0.305129   0.305129    0.0  
min     0.000000   0.000000   0.000000    0.0  
25%     0.000000   0.000000   0.000000    0.0  
50%     0.000000   0.000000   0.000000    0.0  
75%     0.000000   0.000000   0.000000    0.0  
max     1.000000   1.000000   1.000000    0.0

In [26]:
# We are not using the "label" column, so we can drop it
movies.drop('Label', axis = 1, inplace = True)
movies

Movie ID                        Movie Name  IMDB Rating  Biography  Drama  \
0         58                The Imitation Game          8.0          1      1   
1          8                        Ex Machina          7.7          0      1   
2         46                  A Beautiful Mind          8.2          1      1   
3         62                 Good Will Hunting          8.3          0      1   
4         97                      Forrest Gump          8.8          0      1   
5         98                                21          6.8          0      1   
6         31                            Gifted          7.6          0      1   
7          3               Travelling Salesman          5.9          0      1   
8         51                            Avatar          7.9          0      0   
9         47                    The Karate Kid          7.2          0      1   
10        50            A Brilliant Young Mind          7.2          0      1   
11        49                    A Time To Kill          7.4          0      1   
12        30                      Interstellar          8.6          0      1   
13        94           The Wolf of Wall Street          8.2          1      0   
14         6                     Black Panther          7.4          0      0   
15        73                         Inception          8.8          0      0   
16        44                    The Wind Rises          7.8          1      1   
17        65                     Spirited Away          8.6          0      0   
18        48                 Finding Forrester          7.3          0      1   
19        27                      The Fountain          7.3          0      0   
20        57                  The DaVinci Code          6.6          0      0   
21        57                 Stand and Deliver          7.3          0      1   
22        14                    The Terminator          8.0          0      0   
23        69                    21 Jump Street          7.2          0      0   
24        98                      The Avengers          8.1          0      0   
25        17                    Thor: Ragnarok          7.9          0      0   
26        12  Spirit: Stallion of the Cimarron          7.1          0      0   
27         1                     Hacksaw Ridge          8.2          1      1   
28        86                  12 Years a Slave          8.1          1      1   
29        46                    Queen of Katwe          7.4          1      1   

    Thriller  Comedy  Crime  Mystery  History  
0          1       0      0        0        0  
1          0       0      0        1        0  
2          0       0      0        0        0  
3          0       0      0        0        0  
4          0       0      0        0        0  
5          0       0      1        0        1  
6          0       0      0        0        0  
7          0       0      0        1        0  
8          0       0      0        0        0  
9          0       0      0        0        0  
10         0       0      0        0        0  
11         1       0      1        0        0  
12         0       0      0        0        0  
13         0       1      1        0        0  
14         0       0      0        0        0  
15         0       0      0        0        0  
16         0       0      0        0        0  
17         0       0      0        0        0  
18         0       0      0        0        0  
19         0       0      0        0        0  
20         1       0      0        1        0  
21         0       0      0        0        0  
22         0       0      0        0        0  
23         0       1      1        0        0  
24         0       0      0        0        0  
25         0       1      0        0        0  
26         0       0      0        0        0  
27         0       0      0        0        1  
28         0       0      0        0        1  
29         0       0      0        0        0

In [27]:
# Check for null values
movies.isnull().sum()

Movie ID       0
Movie Name     0
IMDB Rating    0
Biography      0
Drama          0
Thriller       0
Comedy         0
Crime          0
Mystery        0
History        0
dtype: int64

### Building Recommendation System

In [28]:
# Identify our columns
movies.columns

Index(['Movie ID', 'Movie Name', 'IMDB Rating', 'Biography', 'Drama',
       'Thriller', 'Comedy', 'Crime', 'Mystery', 'History'],
      dtype='object')

In [29]:
# Definying x and y variable

x = movies[['IMDB Rating', 'Biography', 'Drama',
       'Thriller', 'Comedy', 'Crime', 'Mystery', 'History']]
y = movies['Movie Name']

In [30]:
# Implement nearestneighbor
# Source: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.NearestNeighbors.html
# Source: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

nbrs = NearestNeighbors(n_neighbors=5).fit(x)
distances, indices = nbrs.kneighbors(x)
print(distances)

[[0.         1.0198039  1.0198039  1.16619038 1.41774469]
 [0.         1.00498756 1.07703296 1.07703296 1.11803399]
 [0.         0.4        0.8        1.         1.00498756]
 [0.         0.3        0.5        0.7        1.        ]
 [0.         0.2        0.5        1.         1.0198039 ]
 [0.         1.46969385 1.46969385 1.5        1.5       ]
 [0.         0.3        0.3        0.4        0.4       ]
 [0.         1.57797338 1.64012195 1.64012195 1.72046505]
 [0.         0.1        0.2        0.5        0.6       ]
 [0.         0.         0.1        0.1        0.4       ]
 [0.         0.         0.1        0.1        0.4       ]
 [0.         1.41774469 1.41774469 1.42828569 1.42828569]
 [0.         0.2        0.3        1.         1.        ]
 [0.         1.41421356 1.44568323 1.73205081 1.73493516]
 [0.         0.1        0.3        0.5        0.6       ]
 [0.         0.2        0.7        0.8        0.9       ]
 [0.         0.4        0.4        1.0198039  1.0198039 ]
 [0.         0

Genre Information: "The Post"

IMDB Rating = 7.2, Biography = Yes, Drama = Yes, Thriller = No, Comedy = No, Crime = No, Mystery = No, History = Yes

In [31]:
#define variable for features of "The Post"
the_post = [7.2,1,1,0,0,0,0,1]

distances, indices = nbrs.kneighbors([the_post])
print(indices)

[[28 27 29 16  2]]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  "X does not have valid feature names, but"


In [32]:
# Find recommended movies related to "The Post"
for title in indices:
  print("Movies you might enjoy:")
  print(movies.iloc[title]['Movie Name'])

Movies you might enjoy:
28    12 Years a Slave
27       Hacksaw Ridge
29      Queen of Katwe
16      The Wind Rises
2     A Beautiful Mind
Name: Movie Name, dtype: object


The movies above are recommendations based on watching "The Post". Similar to what Netflix uses after you have finished a show or movie, the movies above will be recommended based on your user patterns.